Refactor Interface, Add Support several types
DeveloperPalmer/Plexus pull request #1
Opened 2024-12-11 08:54 UTC by DeveloperPalmer

2024-12-11 09:01 UTC, DeveloperPalmer commented on app/src/main/java/ru/kode/impl/AppFeature.kt
> +  val type: KClass<@UnsafeVariance T>
Есть как то можно избавиться от этого type и смотреть только на generic, я пока не догнал как можно

2024-12-11 10:10 UTC, DeveloperPalmer commented on app/src/main/java/ru/kode/impl/AppFeature.kt
> +  val type: KClass<@UnsafeVariance T>
Сам коммит если шо можно будет дропнуть, с обработкой других типов, там будет реализация тогда онли на boolean

2024-12-11 10:55 UTC, sdhjfhhsgfk commented on app/src/main/java/ru/kode/plexus/Config.kt
> +  fun getFeatureValue(key: String): Flow<FeatureValue>
если одновременно есть метод для получения значения и метод для получения flow, может заменить одним методом получения StateFlow<FeatureValue> ?

2024-12-11 11:06 UTC, sdhjfhhsgfk commented on app/src/main/java/ru/kode/impl/config/RemoteConfig.kt
> +      }
в обоих случаях одно и то же

2024-12-11 11:12 UTC, sdhjfhhsgfk commented on app/src/main/java/ru/kode/plexus/PlexusManager.kt
> +class PlexusManager internal constructor(
при использовании похожей реализации на проекте столкнулись со следующей ситуацией: старт приложения, на первом же экране сразу надо получить значение фичефлага. и оно всегда было false. оказалось что Firebase Remote Config не получал к тому времени реальные данные и в итоге от менеджера приходило дефолтное значение (false). решили тем, что добавили в менеджер flow, говорящий о том, все ли источники инициализированы. на сколько понимаю, тут такая же ситуация может быть

2024-12-11 11:50 UTC, TrueWarg commented on app/src/main/java/ru/kode/impl/AppFeature.kt
> +  val type: KClass<@UnsafeVariance T>
А нельзя ли обойтись без  type вообще? Я вижу, что ты используешь его только для каста, что можно сделать и без хранения типа в самой фичи.

2024-12-11 11:50 UTC, TrueWarg commented on app/src/main/java/ru/kode/plexus/FeatureValue.kt
> +sealed interface FeatureValue {
Тот самый вопрос: "А что есть feature?" Фича всегда может иметь только одно примитивное значение? Могут ли быть составные или список? Если да, то как это будет выглядеть с использованием FeatureValue?

P.S: Вообще, такое дублирование типов в силед выглядит как-то не гибко, и нужно только на ui слое, но это imho

2024-12-11 12:34 UTC, dimsuz requested changes

2024-12-11 12:34 UTC, dimsuz commented on app/src/main/java/ru/kode/plexus/Config.kt
> +  fun getFeatureValue(key: String): Flow<FeatureValue>
я бы так не делал, это будет требовать от имплементаций создавать лишние абстракции. Например, имплементация может иметь офигенно быстрый способ получить значение фичи не-реактивно, и чуть более медленный для получения реактивно. Так мы будем требовать от неё всегда заворачиваать  во флоу...

2024-12-11 12:34 UTC, dimsuz commented on app/src/main/java/ru/kode/plexus/Config.kt
> +  fun getFeaturesValue(keys: List<String>): Flow<Map<String, FeatureValue>>
```suggestion
  fun getFeatureValues(keys: List<String>): Flow<Map<String, FeatureValue>>
```

2024-12-11 12:34 UTC, dimsuz commented on app/src/main/java/ru/kode/plexus/FeatureValue.kt
> +sealed interface FeatureValue {
Да, лучше оставить только String.

2024-12-11 12:34 UTC, dimsuz commented on app/src/main/java/ru/kode/plexus/Mappers.kt
> +}
чёто странное. почему только Comparable?

Но ваще это лучше убрать, оставить только String и не усложнять :)

2024-12-11 12:34 UTC, dimsuz commented on app/src/main/java/ru/kode/plexus/PlexusBuilder.kt
> +}
лишняя функция, лучше либу минималистичной делать. Если кто-то захочет, сделает себе такую.

Обычно делают такой:

```
Plexus.Builder()
  .addConfig(...)
  .build()
```

можно следовать устоявшимся паттернам тут.

2024-12-11 12:34 UTC, dimsuz commented on app/src/main/java/ru/kode/plexus/PlexusManager.kt
> +  inline fun <reified T : Any> getFeatureValueSync(appFeature: AppFeature<T>): T {
хм, это же код либы, почему оно использует AppFeature из кода sample-приложения?

2024-12-11 12:34 UTC, dimsuz commented on app/src/main/java/ru/kode/plexus/PlexusManager.kt
> +    } ?: throw FeatureNotDeclaredException("AppFeature $appFeature is not declared in more than one config")
сообщение непонятное "не объявлена более чем в одном конфиге", как-то странно грамматически.

к тому же toValueOrNull лучше не вводить, ты же нспроста красивый sealed class сделал, надо when использовать.

2024-12-11 12:34 UTC, dimsuz commented on app/src/main/java/ru/kode/plexus/PlexusManager.kt
> +      featureValues.firstNotNullOfOrNull { it.toValueOrNull(appFeature) }
кажется, тут неправильно логически: первый конфиг, который испустит значение выигрывает, разве это так должно работать? у нас же последовательность и приоритеты есть.

2024-12-11 12:34 UTC, dimsuz commented on app/src/main/java/ru/kode/plexus/PlexusManager.kt
> +  }
очень сложно, надо подумать над этим. Скорее всего тут тоже ошибка, надо ведь чтобы от одного конфига только значение выдавалось всех фич.

2024-12-11 12:34 UTC, dimsuz commented on app/src/main/java/ru/kode/impl/config/DebugConfig.kt
> +      .onStart { emit(Unit) }
это не будет правильно работать, могут теряться значения при подписке. почитай доки к этой функции.

2024-12-11 12:34 UTC, dimsuz commented on app/src/main/java/ru/kode/impl/config/DebugConfig.kt
> +      .onStart { emit(Unit) }
см выше

2024-12-11 12:34 UTC, dimsuz commented on app/src/main/java/ru/kode/impl/config/DebugConfig.kt
> +      .map { keys.associateWith { feature -> getFeatureValueInternal(feature) } }
это некорректная имплементация, надо делать такую, которая сразу все получает префы.

То что ты сделал в интерфейсе метод для получения всех значений разом, предполагает, что имплементация знает как их получать разом быстро.

Ты тут получаешь их по одной, зачем тогда ваще нам метод с Map? По  одной их пользователь может получить и без метода Map в интерфейсе — сделав всё то же самое.

2024-12-11 12:34 UTC, dimsuz commented on app/src/main/java/ru/kode/impl/config/DebugConfig.kt
> +  fun setFeatureEnabledState(key: String, featureValue: FeatureValue) {
непонятно, что за имя. "Установить включенное состояние" — но при чем тут value?

2024-12-11 12:34 UTC, dimsuz commented on app/src/main/java/ru/kode/impl/config/DebugConfig.kt
> +  }
убрать эти две функции, лишняя сложность. Prosto string.

2024-12-11 12:34 UTC, dimsuz commented on app/src/main/java/ru/kode/impl/config/RemoteConfig.kt
> +  }
а зачем они нам в lazy-виде, если мы сразу же их в init инициализируем?

2024-12-11 12:34 UTC, dimsuz commented on app/src/main/java/ru/kode/impl/config/RemoteConfig.kt
> +    )
разве здесь корректно merge испльзовать? это же нарушить последовательность может.

2024-12-11 12:34 UTC, dimsuz commented on app/src/main/java/ru/kode/impl/config/RemoteConfig.kt
> +      getOrNull { asString() } != null -> FeatureValue.StringValue(asString())
тут кстати вроде неправильно: если мы не смогли сконвертить даже в String, то надо выбрасывать исключение, а не хавать его. 

А Undefined надо выдавать конкретно только в одном случае — если ремоут конфиг сказал нам, что значения нет.

То есть не-парсящееся значение нельзя приравнивать к его отсутствию.

2024-12-11 12:35 UTC, DeveloperPalmer commented on app/src/main/java/ru/kode/impl/config/RemoteConfig.kt
> +      }
Тут по идеи надо убрать и просто `onComplete.invoke()` вызывать. Я планировал логи сделать, но видимо на след итерацию отложется

2024-12-11 12:39 UTC, dimsuz commented on app/src/main/java/ru/kode/plexus/PlexusManager.kt
> +class PlexusManager internal constructor(
Вот это, кстати, момент, который в целом на дизайн либы может повлиять.

Как вариант, можно завести каждому конфигу какой-то флаг типа State: Initializing, Ready и если не Ready, то при получении флагов от него, скипать такие.

А! Или ещё проще. Просто Firebase конфиг зная свою эту особенность должен возвращать Undefined до тех пор, пока не будет уверен что всё пофетчено. Это вроде решит проблему без изменения текущего API.

2024-12-11 12:42 UTC, DeveloperPalmer commented on app/src/main/java/ru/kode/impl/config/RemoteConfig.kt
> +  }
к ремоут конфигу мы не только в init обращаемся, а вот настройки думаю да, можно вынести только в init

2024-12-11 14:33 UTC, dimsuz commented on app/src/main/java/ru/kode/impl/config/RemoteConfig.kt
> +  }
Да, но если в init ты обращаешься _всегда_ то в чём смысл lazy?

2024-12-12 11:40 UTC, dimsuz commented on app/src/main/java/ru/kode/plexus/Config.kt
> +}
У меня ещё вопрос созрел: зачем нам нужен вот этот метод с флоу получения всех значений по определённым ключам?

2024-12-12 11:40 UTC, dimsuz commented on app/src/main/java/ru/kode/plexus/Config.kt
> +}
Какие юскейсы (желательно больше одного) это обслуживает?

2025-02-13 16:23 UTC, merged